-- =====================================================================
-- 16_bootstrap_admin : (intentionally no-op)
--
--   admin 부트스트랩 이메일을 코드에 박지 않는다.
--   운영자가 backend/supabase/.env 의 ADMIN_EMAIL 변수를 기준으로
--   Supabase SQL Editor 에서 직접 승격한다. 절차는
--   docs/RELEASE_CHECKLIST.md / docs/E2E_VERIFICATION.md 참조.
--
--   tg_handle_new_user 함수는 20260424000200_profiles.sql 의
--   기본 정의를 그대로 사용한다.
-- =====================================================================
